class CreateArtist < ActiveRecord::Migration[6.1]
  def change
    create_table :artists do |t| #t is a special AR migration object, allows us to add table columns
      t.string :name
      t.string :genre
      t.integer :age
      t.string :hometown
      #id is autogenerated
      #primary key autogenerated
    end
  end
end
